name: search-api

image:
  repository: lbadams2/assessment
  tag: 0.1.7
  pullPolicy: IfNotPresent
replicas: 1

service:  
  externalPort: 80
  internalPort: 8000

ingress:
  class: nginx

resources:
  limits: 
    cpu: 4G
    memory: 2
  requests:
    cpu: .25
    memory: .75G