apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector: 
    app: {{ .Values.name }} # looks for pods with this label
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP